# Generated by Django 2.2.8 on 2020-05-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200523_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Slug',
            field=models.SlugField(default='test-product'),
        ),
    ]
