# Generated by Django 2.2.8 on 2020-05-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Slug',
            new_name='slug',
        ),
    ]
