# Generated by Django 2.2.8 on 2020-05-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200524_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default='Lorem ipsum dolor, sit amet consectetur         adipisicing elit. Repellendus, a quod. Fugit explicabo         soluta deleniti laudantium dignissimos similique blanditiis          beatae repellendus ab ratione accusantium et quos doloremque,         d'),
        ),
    ]
